spring.data.redis.host=redis
spring.data.redis.port=6379
spring.datasource.url=jdbc:postgresql://postgres:5432/urlshrt_db
spring.datasource.username=admin
spring.datasource.password=pass

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs